# Generated by Django 4.1.13 on 2024-05-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="adopted_by",),
    ]
